import {
  X,
  ShieldAlert,
  MapPin,
  Brain,
  Clock3,
  CheckCircle,
} from "lucide-react";

export default function CaseSummaryModal({
  open,
  onClose,
  caseData,
}) {
  if (!open || !caseData) return null;

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm"
      onClick={onClose}
    >
      <div
        className="bg-gray-900 w-[650px] max-w-[95%] rounded-2xl border border-gray-700 shadow-2xl"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex justify-between items-center border-b border-gray-700 p-5">
          <div className="flex items-center gap-3">
            <Brain className="text-cyan-400" size={30} />

            <div>
              <h2 className="text-2xl font-bold text-white">
                AI Investigation Summary
              </h2>

              <p className="text-gray-400 text-sm">
                Generated by CrimeLens AI
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="text-gray-400 hover:text-white"
          >
            <X size={28} />
          </button>
        </div>

        {/* Body */}
        <div className="p-6 space-y-6">
          <div className="grid grid-cols-2 gap-6">
            <div>
              <p className="text-gray-400">Case ID</p>

              <h3 className="text-xl text-cyan-400 font-bold">
                {caseData.id}
              </h3>
            </div>

            <div>
              <p className="text-gray-400">Crime Type</p>

              <h3 className="text-white font-semibold">
                {caseData.crime}
              </h3>
            </div>

            <div className="flex items-center gap-2">
              <MapPin className="text-red-400" />

              <span className="text-white">
                {caseData.location}
              </span>
            </div>

            <div className="flex items-center gap-2">
              <Clock3 className="text-cyan-400" />

              <span className="text-white">
                {caseData.date}
              </span>
            </div>
          </div>

          {/* Threat */}
          <div className="bg-red-500/10 border border-red-500 rounded-xl p-4">
            <div className="flex items-center gap-3">
              <ShieldAlert className="text-red-400" />

              <div>
                <h3 className="text-red-400 font-bold">
                  Threat Level : {caseData.risk}
                </h3>

                <p className="text-gray-300 text-sm mt-1">
                  AI Confidence : {caseData.ai}%
                </p>
              </div>
            </div>
          </div>

          {/* AI Analysis */}
          <div>
            <h3 className="text-xl text-white font-bold mb-4">
              AI Analysis
            </h3>

            <div className="space-y-3 text-gray-300">
              <p>• Pattern matches previous incidents in this area.</p>

              <p>• Similar crimes frequently occur between 8 PM and 11 PM.</p>

              <p>• High probability of repeat offenders.</p>

              <p>• Nearby CCTV cameras available for investigation.</p>

              <p>• Nearby police station can respond within 8 minutes.</p>
            </div>
          </div>

          {/* Recommendations */}
          <div>
            <h3 className="text-xl text-white font-bold mb-4">
              Recommended Actions
            </h3>

            <div className="space-y-3">
              {[
                "Increase patrol frequency",
                "Review nearby CCTV footage",
                "Track repeat offenders",
                "Alert nearby police stations",
              ].map((item) => (
                <div
                  key={item}
                  className="flex items-center gap-3 text-gray-300"
                >
                  <CheckCircle className="text-green-400" size={18} />

                  {item}
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="border-t border-gray-700 p-5 flex justify-end">
          <button
            onClick={onClose}
            className="bg-cyan-600 hover:bg-cyan-700 px-6 py-3 rounded-xl text-white font-semibold"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
}